name: dinov2-sim
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.2.2
  - pytorch::torchvision=0.17.2
  - pytorch::torchaudio=2.2.2
  - conda-forge::opencv=4.9.0
  - conda-forge::ffmpeg=6.1.1
  - numpy=1.26.4
  - pillow=10.2.0
  - scipy=1.12.0
  - pip:
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - tqdm==4.66.2
      - hydra-core==1.3.2
      - typer==0.12.3
      - rich==13.7.1
